### ISSUE TITLE
The function `eicu_data` in `utils/utils_data.py` is undefined

### ISSUE THREAD

**Issue by LumionHXJ** [cuis15/learning-to-collaborate#1]
I found that the `eicu_data` function in `utils/utils_data.py` is not defined. Could you please provide the code for this function? If you cannot upload it due to data privacy concerns, could you describe its functionality in detail so that I can reproduce its results? Thank you.

**Comment by cuis15** [comment]
Thanks for your interests. Because of the clinic data privacy concerns, we were informed not to share any features or other information about the dataset, so we removed the specific definition about the function. For the use of this dataset, it doesn't have any special designs compared to other tabular data. Firstly, we split the data with the hospital_ids, and filled the missing values with the mean； then we randomly select several hospitals. (More implementation details could be found in the paper "Benchmarking machine learning models on eicu critical care dataset.")

**Comment by RedsYee** [comment]
> Thanks for your interests. Because of the clinic data privacy concerns, we were informed not to share any features or other information about the dataset, so we removed the specific definition about the function. For the use of this dataset, it doesn't have any special designs compared to other tabular data. Firstly, we split the data with the hospital_ids, and filled the missing values with the mean； then we randomly select several hospitals. (More implementation details could be found in the paper "Benchmarking machine learning models on eicu critical care dataset.")

Could you pls hospitals id of those 10 selected? Are they chosen randomly or according to a certain logic?
